# Generated by Django 4.0.2 on 2022-02-24 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0003_auto_20171118_0922'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('last_name', models.CharField(max_length=250)),
                ('first_name', models.CharField(max_length=250)),
                ('middle_initial', models.CharField(max_length=1)),
                ('time_stamp', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='QRCode',
        ),
    ]
