# Generated by Django 4.0.2 on 2022-02-25 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0004_attendance_delete_qrcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_level', models.IntegerField()),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='student_id',
            new_name='user_type',
        ),
    ]
