# Generated by Django 4.0.2 on 2022-02-25 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0005_section_rename_student_id_attendance_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='scanner.section'),
            preserve_default=False,
        ),
    ]
